#!/bin/sh
. /etc/functions.sh
include /lib/network/

# script revision: $Revision$

URL="http://wurststulle.dyndns.org/ffmap/build/index.php"

#######
# do not alter variables from here on unless you know what you are doing
UPLOAD_SUCCESSFUL=1
PRETEND_UPLOAD=0
DEBUG=0
QUIET=0
TEMP_DIR=/tmp

for file in $( find /lib/yaffmap/* ! -name *.txt )
do
	. $file
done


upload(){
	[ "$DEBUG" = "1" ] &&	echo "entered upload()"
	
	local error=0 returnstring errorcode errormessage error=0 txurl
  
	rem_trailing_comma
	if [ -n "$1" ]
	then
		txurl="$1"
	else
		txurl="$URL$UPLOADPREFIX$DATA$UPLOADSUFFIX"
	fi

	if [ "$PRETEND_UPLOAD" = "1" ]
	then
		echo "This would have been transmitted without '-p':"
		echo "$txurl"
	else
		returnstring="$( wget -T30 -q -O- $txurl )"
		error=$?

		errorcode=$( echo $returnstring | cut -d"|" -f1 )
		errormessage=$( echo $returnstring | cut -d"|" -f2 )
		SERVER_RESPONSE=$( echo $returnstring | cut -d"|" -f3 )

		if [ "$DEBUG" = "1" ]
		then
			length=${#txurl}
			echo "\$TXURL is $length long"
			echo "upload-string: $txurl"
			echo "error text: $errormessage"
			echo "update returnstring: $SERVER_RESPONSE"
		fi

		if [ ! "$errorcode" = "0" ] 
		then
			echo "Map Server returned error"
			echo 
			echo "Error Code: $errorcode"
			echo 
			echo "Error Text: $errormessage"
			echo 
			echo "Transmit String: $txurl"
			echo
			error=1
		fi
	fi


	DATA=""
	UPLOADSPLITCHECKERROR=""
	[ "$DEBUG" = "1" ] && echo "exiting upload() $error"
	return $error
}

upload_split_check(){
#	[ "$DEBUG" = "1" ] && echo "entering upload_split_check()"
	local error=0
	
	length=${#DATA}
	if [ $length -gt 1500 ]
	then
		upload
		error=$?
		DATA=""
	fi
	
	if [ "$UPLOADSPLITCHECKERROR" -eq 1 ] 
	then
		error=1
	fi
	UPLOADSPLITCHECKERROR=$error
	
#	[ "$DEBUG" = "1" ] && echo "exiting upload_split_check() $error"
	return $error
}

rp_links(){
	local error=0
	
	obj neighbour
		for rp in $ROUTINGPROTOCOLS
		do
			${rp}_links || error=1
		done
	endobj

	upload
	[ $error -eq 0 ] && error=$?

	[ "$DEBUG" = "1" ] && echo "exiting rp_links() $error"	
	return $error
}


getid(){
	local error=0
	eval $( ip addr | awk '
	{
		if($0~/ether/){
			ether=$2 }
		if($0~/inet /){
		  split($2,tmp,"/")
		  ip=tmp[1]
		  if(ether){
				print "macaddr="ether";ip="ip
				exit
			}
		}
	}' )

	[ "$GETIDIP" = "1" ] && ip_addon="&ipv4Addr=$ip"
	
	if upload "$URL?do=getID&macAddr=$macaddr$ip_addon"
	then
		eval "$SERVER_RESPONSE"
		saveid "$id"
	else
		error=1
	fi
	
	[ "$DEBUG" = "1" ] && echo "exiting getid() $error"
	return $error
}


update(){
	[ "$DEBUG" = "1" ] &&	echo "entered update() $1"
	
	local update_mode="$1" error=0

	load_node_data
	if [ "$id" = "0" -o -z "$id" ] 
	then
		[ "$QUIET" = "0" ] && echo "NodeID is 0 or empty. Retrieving a new one"
		getid
		update_mode="full"
	fi

	UPLOADPREFIX="?do=update&node="
	obj -v UPLOADPREFIX
		attr -v UPLOADPREFIX id $id
	
	endobj -v UPLOADSUFFIX
	rem_trailing_comma -v UPLOADSUFFIX
	
	case $update_mode in
		links)
			rp_links || error=1
			rf_links || error=1
			;;
		global)	
			olsr_global_update || error=1
			;;
		upgrade)
			check_new_release
			;;
		* )	
			load_node_data	
			attr updateIntervalNode $nodeinterval
			attr updateIntervalLink $linksinterval
			attr timeout $timeout
			attr hostname $( uname -n )
			[ -n "$lat" ] && attr latitude $lat
			[ -n "$lon" ] && attr longitude $lon
			[ "$isHna" -eq 1 ] && attr isHna true || attr isHna false
			[ -n "$defGateway" ] && attr defGateway $defGateway
			if ! upload; then error=1; ERROR_REASON="$ERROR_REASON node_data"; fi
		
			network_interfaces || error=1
			rp_links || error=1
			rf_links || error=1
			;;
	esac

	[ "$DEBUG" = "1" ] && echo "exiting update() $error"
	return $error
}

check_new_release(){
	local txurl rev
	local started="false"
	
	rel=$(cat /lib/yaffmap/release.txt)
	txurl="${URL}?do=getUpgrade&rel=${rel}&tree=devel&version=uci"
	upload $txurl
	eval $SERVER_RESPONSE #this creates the variable "url"

	upgrade $url	
}

local error=0 usage=0 noerrmsg=0
args=$@

for s in $@
do
	case $s in
		"-q") 
			QUIET=1
			;;
		"-v")	
			DEBUG=1
			;;
		"--getidip")
			GETIDIP=1
			;;
		"-p")
			PRETEND_UPLOAD=1
			;;
	esac
	args=$( echo $args | sed 's/$s//g' )	
done

case $( echo $args | cut -d" " -f1 ) in
	start)
		create_config
		migrate_from_old
		add_to_cron
		noerrmsg=1
		;;
	stop)
		remove_from_cron
		noerrmsg=1
		;;
	update) 
		update $2
		error=$?
		;;
	restart)	
		$0 stop
		[ $? -eq 1 ] && error=1
		$0 start
		[ $? -eq 1 ] && error=1
		;;
	check_new_release)
		check_new_release
		;;
	migrate_from_old)
		migrate_from_old
		;;
	*)	
			echo "usage: $0 [options] start|stop|(update [links|global])|check_new_release|migrate_from_old"
			echo "	options:"
			echo "	-v		show debug output"
			echo "	-q		do not show show success or error messages"
			echo "	-p		data is printed on screen instead of being uploaded"
			echo "	--getidip	use also IP address to retrieve nodeID from map server"
			noerrmsg=1
		;;
esac


if [ $noerrmsg -eq 0 ]
then
	if [ $error -eq 0 ]
	then
		[ "$QUIET" -ne 1 ] && echo "Update Successful"
	else
		echo "Error during update. ERROR_REASON=$ERROR_REASON"
		echo "Please start with argument -v and mail the output to the developers"
	fi
fi