#!/bin/sh

olsr_links(){
	[ "$DEBUG" = "1" ] && echo "entering olsr_links()"
	local config error=0

	for config in /var/etc/olsrd.conf /var/etc/olsrd-ipv6.conf
	do
		if [ -e $config ]
		then
			if ! olsr_links_common $config ; then error=1; ERROR_REASON="$ERROR_REASON olsr_links_common"; fi
		fi
	done

	[ "$DEBUG" = "1" ] && echo "exiting olsr_links() $error"
	return $error
}

olsr_global_update(){
	[ "$DEBUG" = "1" ] && echo "entering olsr_global_update()"
	local error=0
	local suffix 
	local updateintervalglobal ipversion metrictype
	local latlonfile hostsfile

	updateintervalglobal=$( uci get freifunk_map.ffmap.globalinterval 2>/dev/null)
	[ "$FORCE" = "1" ] && [ -z "$updateintervalglobal" ] && updateintervalglobal=0

	get_dnssuffix(){
		config_get suffix "$1" suffix
	}
	config_load olsrd
	config_foreach get_dnssuffix LoadPlugin

	if [ -z "$updateintervalglobal" ]
	then
		echo "No olsr global update without globalinterval"
		error=1
	else
		for olsr_config in /var/etc/olsrd.conf /var/etc/olsrd-ipv6.conf
		do
			if [ -e $olsr_config ]
			then
				metrictype=$( grep LinkQualityAlgorithm $olsr_config | cut -d" " -f2 | sed 's/"//g' )
				ipversion=$( grep IpVersion $olsr_config | cut -d" " -f2 | sed 's/"//g' )
				latlonfile=$( grep latlon-file $olsr_config | cut -d" " -f3 | sed 's/"//g' )
				hostsfile=$( grep hosts-file $olsr_config | cut -d" " -f3 | sed 's/"//g' )
				if ! olsr_global_update_common $updateintervalglobal $suffix $metrictype $ipversion $latlonfile $hostsfile
				then 
					error=1
					ERROR_REASON="$ERROR_REASON olsr_global_update_common"
				fi
			fi
		done
	fi

	[ "$DEBUG" = "1" ] && echo "exiting olsr_global_update() "$error
	return $error
}